### ISSUE TITLE
I does not apear on Musescore plugin manager

### ISSUE THREAD

**Issue by KoldoMZN** [zehanort/flh#1]
I've tryed also by putting it into creator mode and show this
Running…
Creating component failed
   line 102: Unexpected token `>'
   line 107: Unexpected token `>'
   line 112: Unexpected token `>'
   line 152: Unexpected token `>'
   line 163: Unexpected token `>'
   line 163: Expected token `:'
   line 163: Unexpected token `;'
   line 169: Unexpected token `>'
   line 170: Unexpected token `>'
   line 177: Unexpected token `>'
   line 177: Expected token `:'
   line 177: Expected token `}'

**Comment by zehanort** [comment]
Hi @KoldoMZN and thanks for your interest in `FLH`!

Unfortunately, what you have (most probably) encountered is trying to use `FLH` with an old `Qt` version (see the updated version of the `README.md` file for details).

I will try to create a new branch for a "downgraded" version of `FLH` to be compatible with `Qt` versions < 5.12, but I am not sure if I can find the time. Help is always welcome, of course!

Just to make sure, please reply with the platform you are working on (Windows / Linux / Mac) and the `Qt` version that your `MuseScore 3.x` installation uses (top toolbar inside `MuseScore` -> `Help` -> `About Qt...`)

Regarding the fact that you can not see the plugin listed, I am afraid I can not replicate the problem. Have you made sure that you have put `flh.qml` inside the path defined by the Plugin Manager?

**Comment by KoldoMZN** [comment]
I maybe find the problem, I am on windows and it says its using Qt 5.9.9, Its musescore 3.6. Maybe I'll have to downgrade it to Musescore 3.3. I will try

**Comment by KoldoMZN** [comment]
Yeah on musescore 3.3 works perfectly becaus this verison uses the qlt 5.12.5
